permalink: /:categories/:year/:month/:title
highlighter: rouge
gems:
  - jekyll-redirect-from
navigation:
  - title: home
    url: /
  - title: source
    url: "https://github.com/Kevin-Mattheus-Moerman/GIBBON"

<<<<<<< HEAD
theme: jekyll-theme-midnight
=======
theme: jekyll-theme-midnight
>>>>>>> 0049bcab7e83501848848a2d9e920b16d55c0252
